image: python:3.9.16  # The latest python version 3.9.17 throws an error in the CI/CD pipeline

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test

before_script:
  - python --version  # For debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  # - pip install pre-commit
  # - pip install isort
  # - pip install black==23.1.0
  # - pip install flake8
  # - pip install pylint
  - pip install pytest
  - pip install networkx[default]
  - pip install -e .
  - pip install networkit
  - pip install qiskit-aer
  - pip install qiskit_ibm_runtime
  - pip install pennylane
  - pip install pytket
  - pip install pytket-qiskit
  - pip install jax


# isort:
#   stage: linting
#   script:
#     - isort .

# black:
#   stage: linting
#   script:
#     - black --check src/
#     - black --check tests/
#     - black --exclude=´/src/qrisp/interface/´

# flake8:
#   stage: linting
#   script:
#     - flake8 src/
#     - flake8 tests/

# pylint:
#   stage: linting
#   script:
#     - pylint src/

python_test:
    stage: test
    script:
        #- venv install
        - python -m pytest
